/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ENCLAVE_ARGS_H
#define EDGER8R_ENCLAVE_ARGS_H

#include <openenclave/bits/result.h>

/**** User includes. ****/
#include "../enclave/ttt.h"

/**** User defined types in EDL. ****/
/* There were no user defined types. */

#endif // EDGER8R_ENCLAVE_ARGS_H
